.PHONY: test vet build synth demo
test: ; go test ./...
vet:  ; go vet ./...
build: ; mkdir -p bin && go build -o bin/ ./cmd/...
synth: ; go run ./cmd/syngen > testdata/synthetic_day.ndjson
demo: build ; SOURCE=replay REPLAY_FILE=testdata/synthetic_day.ndjson bin/collector | bin/engine > out.ndjson && echo "wrote out.ndjson"
