// classmap writes a PROVISIONAL session calendar: the embedded calendar plus an ins_code → class
// mapping proposed by internal/classmap from SourceArena identity fields (namad_code = ISIN,
// industry_code, full_name), flagged "instruments_verified": false so the dashboard shows
// «نگاشت کلاس تأییدنشده». Abnormal boards, energy and unrecognised rows stay unmapped (class
// unknown, excluded from per-class aggregates). LOCAL use: point SESSIONS_FILE at the output
// for collector, engine and gateway alike.
//
//	go run ./cmd/classmap -sourcearena saved.json -out .local/sessions-provisional.json
//	SOURCEARENA_TOKEN=… go run ./cmd/classmap -out …   # one live request
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"bourse/internal/calendar"
	"bourse/internal/classmap"
)

func main() {
	log.SetFlags(0)
	saFile := flag.String("sourcearena", "", "saved SourceArena all&type=0 payload (default: one live request with SOURCEARENA_TOKEN)")
	out := flag.String("out", ".local/sessions-provisional.json", "sessions file to write")
	flag.Parse()

	body, err := load(*saFile)
	if err != nil {
		log.Fatalf("classmap: %v", err)
	}
	var rows []map[string]any
	if err := json.Unmarshal(body, &rows); err != nil {
		log.Fatalf("classmap: payload is not a JSON array: %v", err)
	}
	m, st := build(rows)
	b, err := provisional(calendar.EmbeddedJSON(), m)
	if err != nil {
		log.Fatalf("classmap: %v", err)
	}
	if _, err := calendar.Parse(b); err != nil {
		log.Fatalf("classmap: generated calendar is invalid: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		log.Fatalf("classmap: %v", err)
	}
	if err := os.WriteFile(*out, b, 0o644); err != nil {
		log.Fatalf("classmap: %v", err)
	}
	fmt.Print(st.String())
	log.Printf("classmap: %d of %d instruments mapped (PROVISIONAL) -> %s", len(m), st.rows, *out)
}

type stats struct {
	rows     int
	byClass  map[string]int
	byGroup  map[string]int
	unmapped map[string][]string // group → sample symbols
}

// build proposes a class per instrument. Rows without instance_code cannot be keyed and are
// counted under "بدون کد".
func build(rows []map[string]any) (map[string]string, stats) {
	st := stats{rows: len(rows), byClass: map[string]int{}, byGroup: map[string]int{}, unmapped: map[string][]string{}}
	m := map[string]string{}
	for _, r := range rows {
		code := text(r, "instance_code")
		g := classmap.Group(text(r, "namad_code"), text(r, "industry_code"), text(r, "full_name"))
		if code == "" {
			g = "بدون کد"
		}
		st.byGroup[g]++
		cl := classmap.Class(g)
		if code == "" || cl == "" {
			st.byClass[calendar.Unknown]++
			if len(st.unmapped[g]) < 5 {
				st.unmapped[g] = append(st.unmapped[g], text(r, "name"))
			}
			continue
		}
		m[code] = cl
		st.byClass[cl]++
	}
	return m, st
}

func (s stats) String() string {
	var b strings.Builder
	fmt.Fprintf(&b, "rows: %d\nper class (PROVISIONAL):\n", s.rows)
	for _, k := range sortedKeys(s.byClass) {
		fmt.Fprintf(&b, "  %-13s %5d\n", k, s.byClass[k])
	}
	b.WriteString("per group:\n")
	for _, k := range sortedKeys(s.byGroup) {
		cl := classmap.Class(k)
		if cl == "" {
			cl = calendar.Unknown
		}
		fmt.Fprintf(&b, "  %5d  %s -> %s\n", s.byGroup[k], k, cl)
	}
	b.WriteString("unmapped (sample symbols):\n")
	for _, k := range sortedKeys(s.unmapped) {
		fmt.Fprintf(&b, "  %s: %s\n", k, strings.Join(s.unmapped[k], "، "))
	}
	return b.String()
}

// provisional returns base with instruments replaced by m (synthetic SYN* entries are dropped:
// they never share a stack with live data) and "instruments_verified": false.
func provisional(base []byte, m map[string]string) ([]byte, error) {
	var top map[string]any
	if err := json.Unmarshal(base, &top); err != nil {
		return nil, err
	}
	top["instruments"] = m
	top["instruments_verified"] = false
	top["_instruments_note"] = "PROVISIONAL («تأییدنشده»): generated by cmd/classmap on " +
		time.Now().UTC().Format("2006-01-02 15:04 UTC") +
		" from SourceArena ISIN/industry_code/full_name (internal/classmap). Not an official list; local use only."
	return json.MarshalIndent(top, "", "  ")
}

func text(r map[string]any, k string) string {
	switch v := r[k].(type) {
	case string:
		return strings.TrimSpace(v)
	case float64:
		return fmt.Sprintf("%.0f", v)
	}
	return ""
}

func sortedKeys[V any](m map[string]V) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

// load reads a saved payload or makes ONE live request; errors never carry the token.
func load(file string) ([]byte, error) {
	if file != "" {
		return os.ReadFile(file)
	}
	token := os.Getenv("SOURCEARENA_TOKEN")
	if token == "" {
		return nil, errors.New("SOURCEARENA_TOKEN is not set (or pass -sourcearena saved.json)")
	}
	base := os.Getenv("SOURCEARENA_URL")
	if base == "" {
		base = "https://apis.sourcearena.ir/api/"
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, base+"?token="+url.QueryEscape(token)+"&all&type=0", nil)
	if err != nil {
		return nil, errors.New("build request failed")
	}
	client := &http.Client{CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	resp, err := client.Do(req)
	if err != nil {
		var ue *url.Error
		if errors.As(err, &ue) {
			err = fmt.Errorf("%s: %w", ue.Op, ue.Err)
		}
		return nil, errors.New(strings.NewReplacer(token, "***", url.QueryEscape(token), "***").Replace(err.Error()))
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 64<<20))
}
